Telegraf docker collector metrics initial commit with integration
logzio/telegraf-docker-collector-metrics pull request #1
Opened 2022-05-17 15:40 UTC by resdenia

2022-05-18 07:47 UTC, mirii1994 requested changes

2022-05-18 07:47 UTC, mirii1994 commented on app.py
> +
Can you add a general `except` line that will catch exceptions that are not `subprocess.CalledProcessError` and `KeyboardInterrupt`, and log them?

2022-05-18 07:47 UTC, mirii1994 commented on app.py
> +                self.configured_data = '\n'.join(paths_conf_done)
Why not use a toml library? Like this one, for example- https://pypi.org/project/toml/ ?
I think it will make the code cleaner.

2022-05-18 07:47 UTC, mirii1994 commented on app.py
> +        w.store_array_in_toml()
Can this be a part of `default params` func? This way you'll only open and save the conf file once, instead of twice.

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +To simplify shipping metrics from one or many sources, we created Docker Metrics Collector. Docker Metrics Collector is a container that runs Telegraf collector.
```suggestion
To simplify shipping metrics from one or many sources, we created Telegraf Docker Metrics Collector. Telegraf Docker Metrics Collector is a container that runs Telegraf collector.
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +## Pull the Docker image of the Telegraf Docker Metrics Collector
```suggestion
## 1. Pull the Docker image
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +## Run the Telegraf Docker Metrics Collector
```suggestion
## 2. Run the collector
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +docker pull logzio/telegraf-docker-collector-metrics
```suggestion
docker pull logzio/telegraf-docker-collector-metrics:latest
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +| LOGZIO_LISTENER | Your Logz.io listener address, For example: `https://listener.logz.io:8053`.                                              |
```suggestion
| LOGZIO_LISTENER | **Default**: `https://listener.logz.io:8053`. Your Logz.io listener address followed by port `8053`.                                             |
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +| METRICS_TOKEN   | Your Logz.io metrics account token. Replace <<METRICS-SHIPPING-TOKEN>> with the token of the account you want to ship to. |
```suggestion
| METRICS_TOKEN   | **Required**. Your Logz.io metrics account token. Replace <<METRICS-SHIPPING-TOKEN>> with the token of the account you want to ship to. |
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +| DOCKER_ENDPOINT | Address to reach the required Docker (default: `unix:///var/run/docker.sock`)Daemon.                                      |
```suggestion
| DOCKER_ENDPOINT | **Default**: default: `unix:///var/run/docker.sock`. Address to reach the required Docker Daemon.                                      |
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +| TIMEOUT         | The request timeout for any Docker Daemon query ( default: `5s`).                                                         |
```suggestion
| TIMEOUT         | **Default**: `5s`. The request timeout for any Docker Daemon query.                                                         |
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +
This newline breakes the table

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +| EXCLUED_IMAGES | A list of strings, [regexes](https://pkg.go.dev/regexp), or [globs](https://github.com/gobwas/glob) whose referent container image names will not be among the queried containers. !
```suggestion
| EXCLUED_IMAGES | **Default**: `nil`. A list of strings, [regexes](https://pkg.go.dev/regexp), or [globs](https://github.com/gobwas/glob) whose referent container image names will not be among the queried containers. !-prefixed negations are possible for all item types to signify that only unmatched container image names should be monitored. For example:`imageNameToExclude1,imageNameToExclude2`) |
```

2022-05-18 07:47 UTC, mirii1994 commented on README.md
> +### Check Logz.io for your metrics
```suggestion
### 4. Check Logz.io for your metrics
```

2022-05-18 15:56 UTC, mirii1994 requested changes

2022-05-18 15:56 UTC, mirii1994 commented on app.py
> +    def set_params(self):
Great! Much more readable!

2022-05-18 20:42 UTC, resdenia commented on README.md
> +
**Can you explain what is broke?**
@mirii1994 

![screencapture-github-logzio-telegraf-docker-collector-metrics-blob-intergation-stage-README-md-2022-05-18-23_41_04](https://user-images.githubusercontent.com/11467909/169152201-dac6ca18-b227-4956-bc11-c27c59716200.png)

2022-05-18 20:53 UTC, resdenia commented
@mirii1994 
Attached readme. You can check also. Can you point me in design what is break?

![screencapture-github-logzio-telegraf-docker-collector-metrics-blob-intergation-stage-README-md-2022-05-18-23_41_04](https://user-images.githubusercontent.com/11467909/169152510-ad1fb475-8661-4ee0-bcbe-38c2f9e56727.png)

2022-05-19 08:14 UTC, mirii1994 approved these changes
Great work.
Make sure that before you're publishing you have the docker images deployed to docker hub, and that you also have an instruction page for this integration in our docs.

2022-05-19 08:14 UTC, mirii1994 commented on README.md
> +
My bad. You're right the table looks good.

2022-05-22 07:44 UTC, merged